baseURL = 'https://example.org/' # your git repository address
title = 'freshpink' # your own blog title

languageCode = 'en-us'
canonifyURLs = true

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'TAGS'
pageRef = '/tags/'
weight = 20

[[menus.main]]
name = 'ABOUT'
pageRef = '/about/'
weight = 30

[module]
  [module.hugoVersion]
    extended = true
    min = '0.116.0'
  [[module.imports]]
    path = 'github.com/elecbrandy/freshpink'

[params]
  googleAnalytics = 'G-000000000' # your GoogleAnalytics code
  githubUsername = 'elecbrandy' # your githubUsername
  copyright = 'Copyright Â© 2024 elecbrandy'
  math = true

[taxonomies]
  tag = 'tags'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
